function errno -a code -d "Return the error number corresponding to an error code"
  set -l codes EPERM ENOENT ESRCH EINTR EIO ENXIO E2BIG ENOEXEC EBADF \
               ECHILD EWOULDBLOCK EAGAIN ENOMEM EACCES EFAULT ENOTBLK EBUSY \
               EEXIST EXDEV ENODEV ENOTDIR EISDIR EINVAL ENFILE EMFILE \
               ENOTTY ETXTBSY EFBIG ENOSPC ESPIPE EROFS EMLINK EPIPE EDOM \
               ERANGE ENOMSG EIDRM ECHRNG EL2NSYNC EL3HLT EL3RST ELNRNG \
               EUNATCH ENOCSI EL2HLT EDEADLK ENOLCK EBADE EBADR EXFULL \
               ENOANO EBADRQC EBADSLT EDEADLOCK EBFONT ENOSTR ENODATA ETIME \
               ENOSR ENONET ENOPKG EREMOTE ENOLINK EADV ESRMNT ECOMM EPROTO \
               EMULTIHOP EDOTDOT EBADMSG ENAMETOOLONG EOVERFLOW ENOTUNIQ \
               EBADFD EREMCHG ELIBACC ELIBBAD ELIBSCN ELIBMAX ELIBEXEC \
               EILSEQ ENOSYS ELOOP ERESTART ESTRPIPE ENOTEMPTY EUSERS \
               ENOTSOCK EDESTADDRREQ EMSGSIZE EPROTOTYPE ENOPROTOOPT \
               EPROTONOSUPPORT ESOCKTNOSUPPORT EOPNOTSUPP EPFNOSUPPORT \
               EAFNOSUPPORT EADDRINUSE EADDRNOTAVAIL ENETDOWN ENETUNREACH \
               ENETRESET ECONNABORTED ECONNRESET ENOBUFS EISCONN ENOTCONN \
               ESHUTDOWN ETOOMANYREFS ETIMEDOUT ECONNREFUSED EHOSTDOWN \
               EHOSTUNREACH EALREADY EINPROGRESS ESTALE EUCLEAN ENOTNAM \
               ENAVAIL EISNAM EREMOTEIO

  if test -z $code
    printf '%s\n' $codes
    return 0
  end

  set -l error_number (contains -i "$code" $codes)
  set -l lookup_status $status

  if test "$lookup_status" != 0
    return 127
  end

  return $error_number
end
